// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 PhoneBridge Contributors
//
// This file is part of PhoneBridge. See LICENSE and the dual-licensing
// notice in README.md for details.

//! Display-endpoint token management.
//!
//! The display endpoint authenticates to the message-center by
//! presenting a shared token in the WS query string
//! (`?token=…`). The token is a 256-bit (32-byte) random
//! value, generated by the message-center at first start and persisted
//! to disk at `~/.config/phonebridge/display.token` (mode
//! 0600 on Unix). The user copies the token to the display
//! endpoint's config; revoking the token (or rotating it)
//! invalidates the URL the display endpoint has on file.
//!
//! Why query-string auth (and not a header)? Because the
//! standard browser `WebSocket` API does not let a JS / native
//! client set arbitrary headers; the WebSocket handshake
//! carries the request line which is the only place a token
//! can be injected. For a LAN tool this is acceptable — the
//! URL is shown once at configuration time, the message-center
//! rejects reuse after rotation, and there is no third party
//! in the path. See `docs/dev-setup.md` for the threat model.
//!
//! The token file is intentionally NOT a config file: it is
//! a credential and lives in a separate path with its own
//! permissions, so the user's other message-center config can be
//! version-controlled without leaking the token.

#![forbid(unsafe_code)]
#![allow(missing_docs)]

use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use parking_lot::RwLock;
use ring::rand::{SecureRandom, SystemRandom};
use tracing::{info, warn};

use phonebridge_core::paths::AppPaths;

use crate::app_state::AppState;

/// File name (relative to the config dir) where the token is
/// persisted. Mode 0600 on Unix.
const TOKEN_FILE: &str = "display.token";

/// Length of the token in bytes. 32 bytes = 256 bits, which
/// is comfortably over the 128-bit minimum recommended for
/// security tokens. The hex-encoded form (used in the URL
/// query string) is 64 chars.
pub const TOKEN_BYTES: usize = 32;

/// Cheaply-cloneable handle to the loaded token. Replaced
/// atomically on rotate / revoke.
#[derive(Clone)]
pub struct DisplayAuth {
    /// Path to the token file (for printing to the user).
    path: PathBuf,
    /// Current valid token, hex-encoded. Wrapped in a lock so
    /// rotate / revoke can swap without a full message-center restart.
    current: std::sync::Arc<RwLock<String>>,
}

impl DisplayAuth {
    /// Load (or generate) the token from disk. Falls back to
    /// "load or generate" on the common case where the file
    /// does not exist yet.
    pub fn load_or_generate(paths: &AppPaths) -> Result<Self> {
        let path = paths.config_dir.join(TOKEN_FILE);
        let token = match std::fs::read_to_string(&path) {
            Ok(s) => {
                let s = s.trim().to_string();
                if s.is_empty() {
                    return Err(anyhow!("display token file is empty: {}", path.display()));
                }
                if !is_valid_hex(&s) {
                    return Err(anyhow!(
                        "display token file contains non-hex content: {}",
                        path.display()
                    ));
                }
                info!(
                    file = %path.display(),
                    "loaded existing display-endpoint token"
                );
                s
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                let s = generate_token_string();
                write_token_file(&path, &s).with_context(|| {
                    format!("writing new display token to {}", path.display())
                })?;
                info!(
                    file = %path.display(),
                    "generated and persisted new display-endpoint token"
                );
                s
            }
            Err(e) => {
                return Err(anyhow!(
                    "reading display token from {}: {e}",
                    path.display()
                ));
            }
        };
        Ok(Self {
            path,
            current: std::sync::Arc::new(RwLock::new(token)),
        })
    }

    /// Path to the token file (for printing in `display-token`).
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Returns the current hex-encoded token. Used by the
    /// `display-token` subcommand to print the value to the
    /// user (with appropriate warning).
    pub fn current(&self) -> String {
        self.current.read().clone()
    }

    /// Verify that a candidate token matches the current one.
    /// Constant-time comparison: we don't want the message-center’s
    /// response timing to leak how many leading bytes match.
    pub fn verify(&self, candidate: &str) -> bool {
        let current = self.current.read();
        // Pad / truncate the candidate to the same length so
        // a length mismatch doesn't short-circuit the equality
        // test. We then do a constant-time XOR-fold compare.
        let cur_bytes = current.as_bytes();
        let cand_bytes = candidate.as_bytes();
        if cand_bytes.len() != cur_bytes.len() {
            return false;
        }
        let mut diff: u8 = 0;
        for (a, b) in cur_bytes.iter().zip(cand_bytes.iter()) {
            diff |= a ^ b;
        }
        diff == 0
    }

    /// Replace the current token with a fresh one. Writes
    /// atomically (write-to-temp + rename) so a crash mid-rotate
    /// cannot leave the file half-written and break the message-center.
    pub fn rotate(&self) -> Result<String> {
        let new_token = generate_token_string();
        write_token_file(&self.path, &new_token).with_context(|| {
            format!("rotating display token at {}", self.path.display())
        })?;
        *self.current.write() = new_token.clone();
        info!(file = %self.path.display(), "rotated display token");
        Ok(new_token)
    }

    /// Invalidate the current token (replaces the file with
    /// a fresh one and updates the in-memory copy).
    pub fn revoke(&self) -> Result<String> {
        // For v1, revoke == rotate: we generate a new random
        // token and overwrite the file. The old token is no
        // longer valid because the message-center only knows the new
        // one. A future "deny-list of revoked tokens" is not
        // needed because the threat model is LAN + single-user.
        self.rotate()
    }
}

/// Decide whether a TCP peer at [SocketAddr] is "the same host"
/// as this process — i.e. the display binary and the message-center
/// are running on the same machine, so the user is implicitly
/// trusted and the token round-trip can be skipped.
///
/// Heuristic: the peer is loopback (127.0.0.0/8, ::1), OR
/// the peer IP matches one of the host's local interface IPs
/// (we enumerate them via [`get_local_addrs`]). This covers the
/// two common patterns:
///
/// 1. `display.toml` says `url = "http://127.0.0.1:8443"` — peer is
///    always `127.0.0.1`, always recognized as same-host.
/// 2. `display.toml` says `url = "http://192.168.1.5:8443"` (the
///    daemon's LAN IP) AND the display runs on the same machine —
///    peer is `192.168.1.5`, which appears in our local
///    interface list.
///
/// Anything else (a foreign IP) returns `false` and the token
/// check proceeds as before. We deliberately err on the side of
/// **requiring** the token when in doubt: a missed
/// same-host optimization only means re-typing a token, while
/// a false positive would let a LAN attacker bypass auth.
pub fn is_same_host(peer: SocketAddr) -> bool {
    let ip = peer.ip();
    if ip.is_loopback() {
        return true;
    }
    if let Ok(addrs) = get_local_addrs() {
        if addrs.contains(&ip) {
            return true;
        }
    }
    false
}

/// Enumerate the host's interface addresses via `nix::ifaddrs`.
/// Loopback is filtered out here (defence in depth on top of
/// `IpAddr::is_loopback`) and only up-and-running interfaces
/// are kept.
fn get_local_addrs() -> Result<Vec<IpAddr>> {
    use nix::net::if_::InterfaceFlags;
    use nix::sys::socket::{AddressFamily, SockaddrLike};
    let mut out = Vec::new();
    for iface in nix::ifaddrs::getifaddrs().context("enumerate interfaces")? {
        if !iface.flags.contains(InterfaceFlags::IFF_UP) {
            continue;
        }
        if iface.flags.contains(InterfaceFlags::IFF_LOOPBACK) {
            continue;
        }
        let Some(sa) = iface.address else { continue };
        let ip = match sa.family() {
            Some(AddressFamily::Inet) => sa
                .as_sockaddr_in()
                .map(|a| IpAddr::V4(a.ip())),
            Some(AddressFamily::Inet6) => sa
                .as_sockaddr_in6()
                .map(|a| IpAddr::V6(a.ip())),
            _ => None,
        };
        if let Some(ip) = ip {
            out.push(ip);
        }
    }
    Ok(out)
}

#[cfg(test)]
mod same_host_tests {
    use super::*;
    use std::net::{Ipv4Addr, Ipv6Addr};

    /// Loopback IPv4 is always same-host.
    #[test]
    fn loopback_v4_is_same_host() {
        let peer: SocketAddr = "127.0.0.1:1234".parse().unwrap();
        assert!(is_same_host(peer));
    }

    /// Loopback IPv6 is always same-host.
    #[test]
    fn loopback_v6_is_same_host() {
        let peer: SocketAddr = "[::1]:1234".parse().unwrap();
        assert!(is_same_host(peer));
    }

    /// The 127.0.0.0/8 range is all loopback; addresses outside
    /// the local interfaces list but inside this range are still
    /// loopback (covered by `IpAddr::is_loopback`).
    #[test]
    fn loopback_range_is_same_host() {
        let peer: SocketAddr = (Ipv4Addr::new(127, 0, 0, 53), 8443).into();
        assert!(is_same_host(peer));
    }

    /// `0.0.0.0` is the unspecified address; `is_loopback()`
    /// returns false, so it falls through to the local-interface
    /// check and is rejected. This is the correct behaviour —
    /// a peer claiming 0.0.0.0 isn't a real client.
    #[test]
    fn unspecified_is_not_same_host() {
        let peer: SocketAddr = (Ipv4Addr::UNSPECIFIED, 8443).into();
        assert!(!is_same_host(peer));
    }

    /// A public/foreign IP that is not on any local interface
    /// must be rejected even if it happens to be the same IP
    /// a reverse proxy uses. We can't make a positive claim
    /// about which IPs are "local" in a unit test (depends on
    /// the host), so we just verify the function runs without
    /// panic and the answer is `false` for a reserved
    /// documentation address that's never on any host.
    #[test]
    fn documentation_ip_is_not_same_host() {
        // 192.0.2.0/24 is TEST-NET-1 (RFC 5737) — guaranteed
        // not to be on any real interface.
        let peer: SocketAddr = (Ipv4Addr::new(192, 0, 2, 1), 8443).into();
        assert!(!is_same_host(peer));
    }

    /// IPv6 documentation prefix (2001:db8::/32) — same idea.
    #[test]
    fn ipv6_documentation_is_not_same_host() {
        let peer: SocketAddr = (Ipv6Addr::new(0x2001, 0xdb8, 0, 0, 0, 0, 0, 1), 8443).into();
        assert!(!is_same_host(peer));
    }
}

fn generate_token_string() -> String {
    let mut bytes = [0u8; TOKEN_BYTES];
    SystemRandom::new()
        .fill(&mut bytes)
        .expect("ring SystemRandom.fill is infallible");
    hex_encode(&bytes)
}

fn is_valid_hex(s: &str) -> bool {
    s.len() == TOKEN_BYTES * 2 && s.bytes().all(|b| b.is_ascii_hexdigit())
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

fn write_token_file(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating parent dir {}", parent.display()))?;
    }
    // Write to a sibling temp file then rename, so a crash
    // mid-write cannot leave a half-written token file.
    let tmp = path.with_extension("token.tmp");
    std::fs::write(&tmp, content)
        .with_context(|| format!("writing temp token file {}", tmp.display()))?;
    // 0600 on Unix. On Windows the mode is ignored; the ACL
    // on the user's home dir already restricts access.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(&tmp, perms)
            .with_context(|| format!("chmod 0600 on {}", tmp.display()))?;
    }
    std::fs::rename(&tmp, path)
        .with_context(|| format!("rename {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// Helper used by the `display-token` subcommand. Wraps the
/// typical "print the current value" workflow so the
/// subcommand's main is short.
pub fn print_current_token(state: &AppState) {
    let token = state.display_auth.current();
    let path = state.display_auth.path();
    println!("# Display-endpoint token (kept on the message-center)");
    println!("# File: {}", path.display());
    println!("# Length: {} hex chars ({} bits)", token.len(), token.len() * 4);
    println!();
    println!("{token}");
    warn!(
        "this token grants read+write access to the message-center over /ws/display; \
         do NOT share it. Rotate with `message-center display-token --rotate`."
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_token_is_hex_and_right_length() {
        let s = generate_token_string();
        assert_eq!(s.len(), TOKEN_BYTES * 2);
        assert!(is_valid_hex(&s));
    }

    #[test]
    fn verify_accepts_exact_match_and_rejects_mismatch() {
        let dir = tempdir_in_target();
        let paths = paths_in(&dir);
        let auth = DisplayAuth::load_or_generate(&paths).unwrap();
        let current = auth.current();
        assert!(auth.verify(&current));
        assert!(!auth.verify("deadbeef"));
        assert!(!auth.verify(""));
    }

    #[test]
    fn rotate_changes_token_and_revokes_old() {
        let dir = tempdir_in_target();
        let paths = paths_in(&dir);
        let auth = DisplayAuth::load_or_generate(&paths).unwrap();
        let old = auth.current();
        let new = auth.rotate().unwrap();
        assert_ne!(old, new);
        assert!(!auth.verify(&old));
        assert!(auth.verify(&new));
    }

    /// Minimal tmp-dir helper for tests; uses the workspace
    /// `target/` so cleanup is automatic with `cargo clean`.
    fn tempdir_in_target() -> PathBuf {
        let base = std::env::var("CARGO_TARGET_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("target"));
        let dir = base.join("test-tmp").join(format!(
            "display-auth-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// Build a minimal `AppPaths` pointing at a tmp dir. We
    /// construct the struct directly because `AppPaths::resolve`
    /// reads env vars and would clobber the real config on a
    /// developer's machine; tests must be hermetic.
    fn paths_in(dir: &Path) -> phonebridge_core::paths::AppPaths {
        phonebridge_core::paths::AppPaths {
            config_dir: dir.to_path_buf(),
            data_dir: dir.to_path_buf(),
            log_dir: dir.to_path_buf(),
        }
    }
}
