// Thin REST client + shared types. Generated by hand; could be replaced
// with a typed fetch wrapper (openapi-typescript, etc.) later.

const API_BASE =
  (typeof process !== "undefined" && process.env.NEXT_PUBLIC_API_BASE) ||
  "https://localhost:8443/api/v1";

const WS_URL =
  (typeof process !== "undefined" && process.env.NEXT_PUBLIC_WS_URL) ||
  "wss://localhost:8443/ws";

export const apiBase = API_BASE;
export const wsUrl = WS_URL;

export interface Health {
  status: string;
  version: string;
  our_device_id: string;
  our_fingerprint: string;
  paired_devices: number;
  online_devices: number;
}

export interface Cert {
  device_id: string;
  name: string;
  fingerprint: string;
  public_key: string;
}

export interface Device {
  id: number;
  name: string;
  device_id: string;
  public_key: string;
  last_seen: number;
  paired: boolean;
}

export interface Notification {
  id: string;
  device_id: string;
  package_name: string;
  app_name: string | null;
  title: string;
  content: string;
  posted_at: number;
  is_sensitive: boolean;
  category: string | null;
  read: boolean;
}

export interface NotificationStats {
  total: number;
  unread: number;
  by_package: Array<{ package: string; count: number }>;
}

export interface Sms {
  id: string;
  device_id: string;
  sim_slot: number | null;
  phone_number: string;
  body: string;
  direction: "in" | "out";
  timestamp: number;
}

export interface SmsConversation {
  address: string;
  last_timestamp: number;
  count: number;
}

export interface Call {
  id: number;
  device_id: string;
  phone_number: string;
  contact_name: string | null;
  state: string;
  started_at: number;
  ended_at: number | null;
  direction: string;
  duration_secs: number | null;
  sim_slot: number | null;
}

export interface Dashboard {
  paired_devices: number;
  online_devices: number;
  notifications: { total: number; unread: number };
  sms: { total: number; conversations: number };
  calls: { total: number; missed: number; ringing: number };
}

export interface AuditEntry {
  id: number;
  timestamp: number;
  device_id: string | null;
  event: string;
  detail: string | null;
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    let body = "";
    try {
      body = await res.text();
    } catch {}
    throw new Error(`${res.status} ${res.statusText}: ${body}`);
  }
  if (res.status === 204) return undefined as T;
  return res.json() as Promise<T>;
}

export const api = {
  health: () => request<Health>("/health"),
  cert: () => request<Cert>("/cert"),
  devices: () => request<{ devices: Device[] }>("/devices"),
  device: (id: string) => request<Device>(`/devices/${id}`),
  removeDevice: (id: string) => request<void>(`/devices/${id}`, { method: "DELETE" }),
  pairings: () => request<{ in_flight: string[]; persisted: unknown[] }>("/pairings"),
  startPair: (device_id: string) =>
    request<{ status: string; device_id: string }>("/pair/start", {
      method: "POST",
      body: JSON.stringify({ device_id }),
    }),
  acceptPair: (device_id: string, code?: string) =>
    request<{ status: string; device_id: string }>("/pair/accept", {
      method: "POST",
      body: JSON.stringify({ device_id, ...(code ? { code } : {}) }),
    }),
  rejectPair: (device_id: string, reason?: string) =>
    request<{ status: string; device_id: string; reason: string }>("/pair/reject", {
      method: "POST",
      body: JSON.stringify({ device_id, reason }),
    }),
  notifications: (params?: { device_id?: string; limit?: number; package?: string; unread_only?: boolean }) => {
    const q = new URLSearchParams();
    if (params?.device_id) q.set("device_id", params.device_id);
    if (params?.limit) q.set("limit", String(params.limit));
    if (params?.package) q.set("package", params.package);
    if (params?.unread_only) q.set("unread_only", "true");
    const qs = q.toString();
    return request<{ notifications: Notification[] }>(`/notifications${qs ? `?${qs}` : ""}`);
  },
  notificationsStats: (params?: { device_id?: string }) => {
    const q = params?.device_id ? `?device_id=${params.device_id}` : "";
    return request<NotificationStats>(`/notifications/stats${q}`);
  },
  markNotificationRead: (device_id: string, id: string) =>
    request<void>(`/notifications/${device_id}/${encodeURIComponent(id)}/read`, {
      method: "POST",
    }),
  dismissNotification: (device_id: string, id: string) =>
    request<{ status: string; device_id: string; id: string; broadcast: boolean }>(
      `/notifications/${device_id}/${encodeURIComponent(id)}/dismiss`,
      { method: "POST" }
    ),
  sms: (params?: { device_id?: string; phone_number?: string; limit?: number }) => {
    const q = new URLSearchParams();
    if (params?.device_id) q.set("device_id", params.device_id);
    if (params?.phone_number) q.set("phone_number", params.phone_number);
    if (params?.limit) q.set("limit", String(params.limit));
    const qs = q.toString();
    return request<{ messages: Sms[] }>(`/sms${qs ? `?${qs}` : ""}`);
  },
  smsConversations: (params?: { device_id?: string }) => {
    const q = params?.device_id ? `?device_id=${params.device_id}` : "";
    return request<{ conversations: SmsConversation[] }>(`/sms/conversations${q}`);
  },
  sendSms: (req: { device_id: string; to: string; body: string; subscription_id?: number }) =>
    request<{ status: string; request_id: string }>("/sms", {
      method: "POST",
      body: JSON.stringify(req),
    }),
  calls: (params?: { device_id?: string; limit?: number }) => {
    const q = new URLSearchParams();
    if (params?.device_id) q.set("device_id", params.device_id);
    if (params?.limit) q.set("limit", String(params.limit));
    const qs = q.toString();
    return request<{ calls: Call[] }>(`/calls${qs ? `?${qs}` : ""}`);
  },
  dial: (device_id: string, number: string) =>
    request<{ status: string; device_id: string; number: string }>("/dial", {
      method: "POST",
      body: JSON.stringify({ device_id, number }),
    }),
  dashboard: (params?: { device_id?: string }) => {
    const q = params?.device_id ? `?device_id=${params.device_id}` : "";
    return request<Dashboard>(`/dashboard${q}`);
  },
  audit: (params?: { limit?: number }) => {
    const q = params?.limit ? `?limit=${params.limit}` : "";
    return request<{ entries: AuditEntry[] }>(`/audit${q}`);
  },
};
